### PR TITLE
9.0.10 firmware

### PR DESCRIPTION
**Pull request by OneNormalUsername**
OnePlus released OxygenOS 9.0.10 for OnePlus 5 and 5T https://www.xda-developers.com/oxygenos-oneplus-5-5t-december-security/

### CODE REVIEW

**Comment by angela-d** [comment]
I'm still seeing 9.0.10 for 5, 9.0.9 for 5T on [Oneplus' site](https://www.oneplus.com/support/softwareupgrade)

Is XDA referencing a beta update? (Which would be weird, for a security patch)

**Comment by OneNormalUsername** [comment]
OnePlus just don't publish builds on their support website immediately after release as they like to do a staged rollout.
You can find official thread at https://forums.oneplus.com/threads/oxygenos-9-0-10-ota-for-the-oneplus-5-and-oneplus-5t.1155523/ (which was published after I opened that pull request)

**Comment by angela-d** [comment]
I see!  I wasn't aware of that, I've never ventured into their forum much before and I typically update a week or two after a release is pushed to my phone, anyway.  I'll merge this now.

Thanks for the info and submitting the update!

**Comment by angela-d** [comment]
Should have hit the merge button, first

**Pull request merged**
